apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: default
  labels:
    type: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:10-beta3
        imagePullPolicy: IfNotPresent
        name: postgres
        env:
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_PASSWORD
          value: "test"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  type: NodePort
  ports:
  - port : 5432
    targetPort: 5432
    protocol: TCP
    name: app
  selector:
    app: postgres