apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: default
  labels:
    type: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.2
        imagePullPolicy: IfNotPresent
        name: mysql
        args:
        - "mysqld"
        - "--max-connections=100"
        - "--innodb_buffer_pool_size=2G"
        - "--innodb_log_file_size=1G"
        - "--innodb_flush_method=O_DIRECT"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "test"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  type: NodePort
  ports:
  - port : 3306
  selector:
    app: mysql