apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mssql
  namespace: default
  labels:
    type: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - image: microsoft/mssql-server-linux:rc2
        imagePullPolicy: IfNotPresent
        name: mssql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "thank5MsSQLforcingMe"
        resources:
          requests:
            memory: "3.3Gi"
            cpu: "0.5"
          limits:
            memory: "3.5Gi"
            cpu: "1"
        ports:
        - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: default
spec:
  type: NodePort
  ports:
  - port : 1433
    targetPort: 1433
    protocol: TCP
    name: app
  selector:
    app: mssql